// Constantes pour les 7 plateformes managées (immuable)
// Données synchronisées depuis GitHub - 8 Février 2026
export const MANAGED_PLATFORMS = [
  {
    key: "emotionscare",
    name: "EmotionsCare",
    shortDescription: "Bien-être émotionnel des soignants et étudiants en médecine",
    description: "Première plateforme française dédiée au bien-être émotionnel des soignants et étudiants en médecine. 37 modules intégrés : scan émotionnel par IA, coaching personnalisé avec Nyvée, musicothérapie, réalité virtuelle et gamification. Conçu pour réduire l'épuisement professionnel et renforcer la résilience au quotidien.",
    tagline: "Prendre soin de celles et ceux qui prennent soin",
    github: "https://github.com/laeticiamng/emotionscare",
    liveUrl: "https://emotionscare.com",
    color: "bg-status-green",
    stats: { modules: 37, tables: 723, edgeFunctions: 261, branches: 635, commits: 7723, tests: 294 },
    features: ["Scan émotionnel IA", "Coach IA Nyvée", "Musicothérapie Suno", "Dashboard B2B RH", "Gamification XP"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "nearvity",
    name: "NEARVITY",
    shortDescription: "Connexion sociale en temps réel pour étudiants",
    description: "Application mobile de connexion sociale en temps réel pour étudiants. Un radar intelligent détecte qui est disponible autour de vous selon 3 signaux (ouvert, conditionnel, occupé). Sessions en binôme, mode fantôme et messagerie de groupe pour des rencontres authentiques sur le campus.",
    tagline: "Connecte-toi avec les gens autour de toi",
    github: "https://github.com/laeticiamng/nearvity",
    liveUrl: "https://nearvity.lovable.app",
    color: "bg-status-amber",
    stats: { modules: 10, tables: 15, edgeFunctions: 8, branches: 4, commits: 847, tests: 42 },
    features: ["Radar temps réel", "3 états de signal", "Sessions binôme", "Ghost mode", "Export GDPR"],
    status: "prototype",
    lastCommit: "2026-01-27",
  },
  {
    key: "system-compass",
    name: "System Compass",
    shortDescription: "Intelligence décisionnelle pour la relocalisation internationale",
    description: "Intelligence décisionnelle pour la relocalisation internationale. Analyse personnalisée de 50+ pays avec simulation fiscale, comparaison qualité de vie et recommandations sur mesure. Pour expatriés, nomades digitaux, entrepreneurs et institutions cherchant le meilleur alignement pays-profil.",
    tagline: "Navigue les systèmes-pays avec intelligence",
    github: "https://github.com/laeticiamng/system-compass",
    liveUrl: "https://world-alignment.lovable.app",
    color: "bg-primary",
    stats: { modules: 20, tables: 57, edgeFunctions: 25, branches: 1, commits: 1272, tests: 718 },
    features: ["Exit Keys personnalisées", "Profils 50+ pays", "Simulateur fiscal", "TraceOS audit", "Life Game gamifié"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "growth-copilot",
    name: "Growth Copilot",
    shortDescription: "39 experts IA couvrant 11 départements métier",
    description: "Votre équipe de 39 experts IA prêts à l'emploi. 2 directeurs et 37 agents spécialisés couvrent 11 départements : marketing, ventes, finance, produit, engineering et plus. Chaque tâche est validée, tracée et automatisée. La compétence premium d'une équipe complète, sans la complexité.",
    tagline: "Compétence premium, livrée simplement",
    github: "https://github.com/laeticiamng/growth-copilot",
    liveUrl: "https://www.agent-growth-automator.com",
    color: "bg-accent",
    stats: { modules: 11, tables: 30, edgeFunctions: 25, branches: 5, commits: 2134, tests: 128 },
    features: ["39 experts IA (2 Dir + 37 Dept)", "11 départements métier", "Validation présidentielle", "Commandes vocales", "Planification automatisée"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "med-mng",
    name: "Med MNG",
    shortDescription: "Apprentissage médical révolutionnaire par la musique IA",
    description: "Révolution de l'apprentissage médical par la musique. Chaque item ECN/EDN devient une chanson générée par IA que vous retenez naturellement. Copilote médical intelligent pour la recherche, la révision et la compréhension. L'anti-panique cognitif des futurs médecins — sécurité certifiée A+.",
    tagline: "Une chanson = Un item médical maîtrisé",
    github: "https://github.com/laeticiamng/med-mng",
    liveUrl: "https://medmng.com",
    color: "bg-destructive",
    stats: { modules: 15, tables: 50, edgeFunctions: 30, branches: 238, commits: 4522, tests: 156 },
    features: ["Copilote médical IA", "Génération musicale IA", "Écoute en continu", "Recherche médicale IA", "Disponible hors connexion"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "swift-care-hub",
    name: "Swift Care Hub",
    shortDescription: "Pilotage intelligent des urgences hospitalières",
    description: "Solution de pilotage des urgences hospitalières. Triage intelligent par IA, suivi des flux patients en temps réel, coordination des équipes soignantes et tableaux de bord de performance. Chaque seconde gagnée peut sauver une vie.",
    tagline: "Chaque seconde compte aux urgences",
    github: "https://github.com/laeticiamng/swift-care-hub",
    liveUrl: "https://flow-pulse-assist.lovable.app",
    color: "bg-destructive",
    stats: { modules: 8, tables: 12, edgeFunctions: 6, branches: 3, commits: 320, tests: 45 },
    features: ["Triage IA intelligent", "Flux patients temps réel", "Coordination équipes", "Analytics urgences", "Alertes critiques"],
    status: "prototype",
    lastCommit: "2026-02-05",
  },
  {
    key: "track-triumph-tavern",
    name: "Track Triumph Tavern",
    shortDescription: "Suivi de performances gamifié pour équipes",
    description: "Plateforme de suivi de performances qui transforme chaque objectif en défi motivant. Classements dynamiques, récompenses personnalisées et progression communautaire. Suivez vos performances en temps réel et célébrez chaque victoire avec votre équipe.",
    tagline: "Chaque victoire mérite d'être célébrée",
    github: "https://github.com/laeticiamng/track-triumph-tavern",
    liveUrl: "https://track-triumph-tavern.lovable.app",
    color: "bg-accent",
    stats: { modules: 12, tables: 18, edgeFunctions: 10, branches: 6, commits: 580, tests: 72 },
    features: ["Classements dynamiques", "Défis personnalisés", "Système de récompenses", "Analytics avancées", "Progression communautaire"],
    status: "production",
    lastCommit: "2026-02-05",
  },
] as const;

// Profil de l'entreprise (données légales)
export const COMPANY_PROFILE = {
  legalName: "EMOTIONSCARE SASU",
  form: "SASU",
  siren: "944 505 445",
  siret: "944 505 445 00014",
  vat: "FR71944505445",
  address: "APPARTEMENT 1, 5 RUE CAUDRON, 80000 AMIENS",
  activity: "58.29C — Édition de logiciels applicatifs",
  capital: "100,00 €",
  creationDate: "07/05/2025",
  rcs: "Amiens (inscrit le 21/05/2025)",
  president: "Motongane Laeticia",
} as const;

export type PlatformKey = typeof MANAGED_PLATFORMS[number]["key"];
