// Constantes pour les 5 plateformes managées (immuable)
// Données synchronisées depuis GitHub - 5 Février 2026
export const MANAGED_PLATFORMS = [
  {
    key: "emotionscare",
    name: "EmotionsCare",
    shortDescription: "Bien-être émotionnel pour professionnels de santé",
    description: "Plateforme de gestion du bien-être émotionnel pour les professionnels de santé et étudiants en médecine. 37 modules (Scan IA, Coach Nyvée, Musicothérapie, VR, Gamification XP). Stack : React 18, Supabase, 261 Edge Functions, 723 tables, 7 723 commits, 294 tests.",
    tagline: "Prendre soin de celles et ceux qui prennent soin",
    github: "https://github.com/laeticiamng/emotionscare",
    liveUrl: "https://emotionscare.com",
    color: "bg-status-green",
    stats: { modules: 37, tables: 723, edgeFunctions: 261, branches: 635, commits: 7723, tests: 294 },
    features: ["Scan émotionnel IA", "Coach IA Nyvée", "Musicothérapie Suno", "Dashboard B2B RH", "Gamification XP"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "pixel-perfect-replica",
    name: "Pixel Perfect Replica",
    shortDescription: "App sociale radar temps réel pour étudiants",
    description: "PWA mobile-first de connexion sociale. Radar temps réel pour visualiser les personnes disponibles autour de toi (3 états : ouvert, conditionnel, occupé). Sessions binôme, ghost mode, chat de groupe. Stack : React 18, Mapbox, Lovable Cloud, 15 tables, 8 Edge Functions.",
    tagline: "Connecte-toi avec les gens autour de toi",
    github: "https://github.com/laeticiamng/pixel-perfect-replica",
    liveUrl: "https://pixel-perfect-clone-6574.lovable.app",
    color: "bg-status-amber",
    stats: { modules: 10, tables: 15, edgeFunctions: 8, branches: 4, commits: 847, tests: 42 },
    features: ["Radar temps réel", "3 états de signal", "Sessions binôme", "Ghost mode", "Export GDPR"],
    status: "prototype",
    lastCommit: "2026-01-27",
  },
  {
    key: "system-compass",
    name: "System Compass",
    shortDescription: "Intelligence relocalisation internationale",
    description: "Plateforme d'aide à la décision pour relocalisation internationale (B2C expats/nomades, B2B entrepreneurs/institutions). Exit Keys personnalisées, analyse 50+ pays, simulation fiscale, gamification. 1 272 commits, 718 tests passants, 103 routes lazy-loaded, 57 tables avec RLS, 25 Edge Functions.",
    tagline: "Navigue les systèmes-pays avec intelligence",
    github: "https://github.com/laeticiamng/system-compass",
    liveUrl: "https://world-alignment.lovable.app",
    color: "bg-primary",
    stats: { modules: 20, tables: 57, edgeFunctions: 25, branches: 1, commits: 1272, tests: 718 },
    features: ["Exit Keys personnalisées", "Profils 50+ pays", "Simulateur fiscal", "TraceOS audit", "Life Game gamifié"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "growth-copilot",
    name: "Growth Copilot",
    shortDescription: "Système d'exploitation d'entreprise avec 39 employés IA",
    description: "Growth OS : 39 employés IA premium (2 Direction CGO/QCO + 37 agents répartis dans 11 départements). Core OS avec RBAC, Approval Gate, Audit Log, Scheduler. 30 tables, 25 Edge Functions. Automatisation complète Marketing, Ventes, Finance, Produit, Engineering.",
    tagline: "Compétence premium, livrée simplement",
    github: "https://github.com/laeticiamng/growth-copilot",
    liveUrl: "https://www.agent-growth-automator.com",
    color: "bg-accent",
    stats: { modules: 11, tables: 30, edgeFunctions: 25, branches: 5, commits: 2134, tests: 128 },
    features: ["39 employés IA (2 Dir + 37 Dept)", "11 départements métier", "Approval Gate", "Voice Commands", "Scheduler automatisé"],
    status: "production",
    lastCommit: "2026-02-05",
  },
  {
    key: "med-mng",
    name: "Med MNG",
    shortDescription: "Apprentissage médical par musique IA",
    description: "Plateforme anti-panique cognitive pour étudiants en médecine (ECN/EDN). Une chanson = un item médical maîtrisé. Medical AI Copilot (GPT-4o, Perplexity, Firecrawl), streaming SSE, génération musicale IA. 4 522 commits, 50 tables, 30 Edge Functions. Score audit 20/20, Grade Sécurité A+.",
    tagline: "Une chanson = Un item médical maîtrisé",
    github: "https://github.com/laeticiamng/med-mng",
    liveUrl: "https://medmng.com",
    color: "bg-destructive",
    stats: { modules: 15, tables: 50, edgeFunctions: 30, branches: 238, commits: 4522, tests: 156 },
    features: ["Medical AI Copilot", "Génération musicale IA", "Streaming SSE", "Mode recherche Perplexity", "PWA offline"],
    status: "production",
    lastCommit: "2026-02-05",
  },
] as const;

// Profil de l'entreprise (données légales)
export const COMPANY_PROFILE = {
  legalName: "EMOTIONSCARE SASU",
  form: "SASU",
  siren: "944 505 445",
  siret: "944 505 445 00014",
  vat: "FR71944505445",
  address: "APPARTEMENT 1, 5 RUE CAUDRON, 80000 AMIENS",
  activity: "58.29C — Édition de logiciels applicatifs",
  capital: "100,00 €",
  creationDate: "07/05/2025",
  rcs: "Amiens (inscrit le 21/05/2025)",
  president: "Motongane Laeticia",
} as const;

export type PlatformKey = typeof MANAGED_PLATFORMS[number]["key"];
