// Constantes pour les 10 plateformes managées (immuable)
// Données synchronisées depuis les sites live — 9 Mars 2026
export const MANAGED_PLATFORMS = [
  {
    key: "emotionscare",
    name: "EmotionsCare",
    shortDescription: "Gérez votre stress en 3 minutes par jour",
    description: "Plateforme de gestion du stress et du bien-être émotionnel pour les soignants et étudiants en médecine. Respiration guidée, coaching IA personnalisé, exercices anti-stress et suivi émotionnel quotidien. 37 modules intégrés pour réduire le burnout.",
    tagline: "Gérez votre stress en 3 minutes",
    github: "https://github.com/laeticiamng/emotionscare",
    liveUrl: "https://emotionscare.com",
    color: "bg-status-green",
    stats: { modules: 37, tables: 723, edgeFunctions: 261, branches: 635, commits: 7723, tests: 294 },
    features: ["Respiration guidée", "Coaching IA personnalisé", "Exercices anti-stress", "Suivi émotionnel quotidien", "Progression & récompenses"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "nearvity",
    name: "NEARVITY",
    shortDescription: "Trouve quelqu'un pour faire des choses, maintenant",
    description: "Application mobile de connexion sociale en temps réel pour étudiants. Un radar intelligent détecte qui est disponible autour de vous. Sessions en binôme, mode discret et messagerie de groupe pour des rencontres authentiques sur le campus.",
    tagline: "Find someone to do things with, right now",
    github: "https://github.com/laeticiamng/pixel-perfect-clone",
    liveUrl: "https://nearvity.lovable.app",
    color: "bg-status-amber",
    stats: { modules: 10, tables: 15, edgeFunctions: 8, branches: 4, commits: 847, tests: 42 },
    features: ["Radar temps réel", "Statuts de disponibilité", "Sessions binôme", "Mode discret", "Conformité RGPD"],
    status: "prototype",
    lastCommit: "2026-01-27",
  },
  {
    key: "system-compass",
    name: "System Compass",
    shortDescription: "Comparez 80+ pays avant de vous expatrier",
    description: "Intelligence décisionnelle pour la relocalisation internationale. Analyse personnalisée de 80+ pays avec simulation fiscale, comparaison qualité de vie et recommandations sur mesure. Pour expatriés, nomades digitaux, entrepreneurs et institutions.",
    tagline: "Comparez les pays avant de partir",
    github: "https://github.com/laeticiamng/system-compass",
    liveUrl: "https://world-alignment.lovable.app",
    color: "bg-primary",
    stats: { modules: 20, tables: 57, edgeFunctions: 25, branches: 1, commits: 1272, tests: 718 },
    features: ["Analyse pays personnalisée", "Profils 80+ pays", "Simulateur fiscal", "Traçabilité des décisions", "Parcours interactif"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "growth-copilot",
    name: "Growth Copilot",
    shortDescription: "39 agents IA pour automatiser votre croissance",
    description: "Votre équipe de 39 agents IA prêts à l'emploi couvrant 11 départements : marketing, ventes, finance, produit, engineering et plus. Chaque tâche est validée, tracée et automatisée pour accélérer votre croissance.",
    tagline: "Automatisez votre croissance avec 39 agents IA",
    github: "https://github.com/laeticiamng/growth-copilot",
    liveUrl: "https://www.agent-growth-automator.com",
    color: "bg-accent",
    stats: { modules: 11, tables: 30, edgeFunctions: 25, branches: 5, commits: 2134, tests: 128 },
    features: ["39 agents IA", "11 départements métier", "Validation dirigeant", "Commandes vocales", "Planification automatisée"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "med-mng",
    name: "Med MNG",
    shortDescription: "Apprends la médecine en musique — 367 cours",
    description: "Révolution de l'apprentissage médical par la musique. 367 cours du programme médical transformés en chansons générées par IA que vous retenez naturellement. Assistant médical intelligent pour la recherche, la révision et la compréhension.",
    tagline: "Apprends la médecine en musique",
    github: "https://github.com/laeticiamng/med-mng",
    liveUrl: "https://medmng.com",
    color: "bg-destructive",
    stats: { modules: 15, tables: 50, edgeFunctions: 30, branches: 238, commits: 4522, tests: 156 },
    features: ["367 cours en musique", "Assistant médical IA", "Génération musicale IA", "Recherche médicale IA", "Disponible hors connexion"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "swift-care-hub",
    name: "UrgenceOS",
    shortDescription: "Le logiciel des urgences que votre hôpital contrôle",
    description: "Application temps réel qui digitalise l'ensemble du parcours patient aux urgences — de l'admission à la sortie. Board panoramique par zone, dossier patient avec timeline médicale, pancarte soignant en 1 tap, tri intelligent.",
    tagline: "Le logiciel des urgences que votre hôpital contrôle",
    github: "https://github.com/laeticiamng/swift-care-hub",
    liveUrl: "https://flow-pulse-assist.lovable.app",
    color: "bg-destructive",
    stats: { modules: 7, tables: 12, edgeFunctions: 6, branches: 3, commits: 320, tests: 45 },
    features: ["Board panoramique temps réel", "Pancarte soignant 1 tap", "Tri intelligent", "Dossier patient complet", "Traçabilité médicale"],
    status: "prototype",
    lastCommit: "2026-03-09",
  },
  {
    key: "track-triumph-tavern",
    name: "Track Triumph",
    shortDescription: "Le seul concours musical 100% communautaire — €200/semaine",
    description: "Plateforme de compétition musicale où les artistes soumettent leurs morceaux chaque semaine et la communauté vote. Feed immersif, notation multi-critères, classements hebdomadaires, Hall of Fame et prix de €200 par semaine pour le vainqueur.",
    tagline: "Le seul concours musical 100% communautaire",
    github: "https://github.com/laeticiamng/track-triumph-tavern",
    liveUrl: "https://track-triumph-tavern.lovable.app",
    color: "bg-accent",
    stats: { modules: 12, tables: 18, edgeFunctions: 10, branches: 6, commits: 580, tests: 72 },
    features: ["Soumissions hebdomadaires", "Votes communautaires", "Prix €200/semaine", "Hall of Fame", "Analyse IA de vos morceaux"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "trust-seal-chain",
    name: "Gouvernance Agents IA",
    shortDescription: "Prouvez que vos agents IA respectent la loi",
    description: "Plateforme de certification et de traçabilité pour les agents IA. Registre de confiance, audit automatisé des décisions algorithmiques, scoring éthique et conformité réglementaire européenne (AI Act).",
    tagline: "Prouvez que vos agents IA respectent la loi",
    github: "https://github.com/laeticiamng/trust-seal-chain",
    liveUrl: "https://trust-seal-chain.lovable.app",
    color: "bg-platform-governance",
    stats: { modules: 8, tables: 20, edgeFunctions: 12, branches: 3, commits: 450, tests: 85 },
    features: ["Certification de confiance", "Traçabilité des décisions IA", "Scoring éthique", "Conformité AI Act", "Registre des agents"],
    status: "prototype",
    lastCommit: "2026-03-09",
  },
  {
    key: "studybeats",
    name: "StudyBeats",
    shortDescription: "Transforme tes cours en chansons — 1200+ créées",
    description: "Transformez vos cours en chansons mémorables. Uploadez vos notes, choisissez parmi 30 styles musicaux, et l'IA génère des paroles éducatives. Plus de 1200 chansons créées et 500+ étudiants actifs.",
    tagline: "Turn your notes into songs",
    github: "https://github.com/laeticiamng/learn-jams",
    liveUrl: "https://learn-jams.lovable.app",
    color: "bg-primary",
    stats: { modules: 8, tables: 15, edgeFunctions: 10, branches: 2, commits: 500, tests: 60 },
    features: ["30 styles musicaux", "Import PDF / photo / texte", "Quiz automatiques", "1200+ chansons créées", "500+ étudiants actifs"],
    status: "production",
    lastCommit: "2026-03-09",
  },
  {
    key: "vascular-atlas",
    name: "Vascular Atlas",
    shortDescription: "Plateforme clinique IA pour la médecine vasculaire",
    description: "Plateforme clinique augmentée par l'IA pour la médecine vasculaire. Assistant clinique IA, modélisation vasculaire 3D, registre mondial des résultats, formation continue et réseau d'experts internationaux.",
    tagline: "L'excellence vasculaire, augmentée par l'IA",
    github: "https://github.com/laeticiamng/vessel-pathway-compass",
    liveUrl: "https://vessel-pathway-compass.lovable.app",
    color: "bg-destructive",
    stats: { modules: 6, tables: 10, edgeFunctions: 5, branches: 2, commits: 150, tests: 30 },
    features: ["Assistant clinique IA", "Modélisation vasculaire 3D", "Registre mondial des résultats", "Formation continue", "Simulation clinique"],
    status: "prototype",
    lastCommit: "2026-03-09",
  },
] as const;

// Profil de l'entreprise (données légales)
export const COMPANY_PROFILE = {
  legalName: "EMOTIONSCARE SASU",
  form: "SASU",
  siren: "944 505 445",
  siret: "944 505 445 00014",
  vat: "FR71944505445",
  address: "APPARTEMENT 1, 5 RUE CAUDRON, 80000 AMIENS",
  activity: "58.29C — Édition de logiciels applicatifs",
  capital: "100,00 €",
  creationDate: "07/05/2025",
  rcs: "Amiens (inscrit le 21/05/2025)",
  president: "Motongane Laeticia",
  linkedinPresident: "https://www.linkedin.com/in/laeticiamotongane/",
  linkedinCompany: "https://www.linkedin.com/company/emotionscare/",
  // Identité professionnelle vérifiée — registre officiel suisse MedReg
  // (Confédération suisse — Plateforme des professions de la santé).
  // Preuve publique d'inscription au registre des médecins, vérifiable
  // par n'importe qui via le numéro GLN (Global Location Number).
  presidentMedRegName: "Moto-Ngane Laëticia Jeanne-Inès",
  presidentMedRegProfession: "Médecin",
  presidentMedRegGLN: "7601009569944",
  presidentMedRegRegistry: "MedReg — Confédération suisse",
  presidentMedRegUrl:
    "https://www.healthregs.admin.ch/MedReg/Search/Person/7601009569944",
} as const;

export type PlatformKey = typeof MANAGED_PLATFORMS[number]["key"];