// Coûts estimés par run type (€) — miroir de src/lib/run-types-registry.ts
// Source unique côté backend pour évaluation budget temps réel.
export const COST_ESTIMATES: Record<string, number> = {
  DAILY_EXECUTIVE_BRIEF: 0.10,
  CEO_STANDUP_MEETING: 0.05,
  PLATFORM_STATUS_REVIEW: 0.02,
  SECURITY_AUDIT_RLS: 0.18,
  RELEASE_GATE_CHECK: 0.12,
  DEPLOY_TO_PRODUCTION: 0.15,
  RLS_POLICY_UPDATE: 0.20,
  COMPETITIVE_ANALYSIS: 0.25,
  QUALITY_AUDIT: 0.15,
  ADS_PERFORMANCE_REVIEW: 0.10,
  GROWTH_STRATEGY_REVIEW: 0.22,
  OKR_QUARTERLY_REVIEW: 0.08,
  COMPLIANCE_RGPD_CHECK: 0.16,
  SEO_AUDIT: 0.20,
  CONTENT_CALENDAR_PLAN: 0.06,
  REVENUE_FORECAST: 0.14,
  LEAD_SCORING_UPDATE: 0.07,
  FINANCIAL_REPORT: 0.12,
  RGPD_AUDIT: 0.16,
  VULNERABILITY_SCAN: 0.18,
  ROADMAP_UPDATE: 0.08,
  CODE_REVIEW: 0.12,
  DEPLOYMENT_CHECK: 0.06,
  DATA_INSIGHTS_REPORT: 0.14,
  AGENT_PERFORMANCE_REVIEW: 0.08,
  TECH_WATCH_REPORT: 0.10,
  MARKETING_WEEK_PLAN: 0.04,
  MASS_EMAIL_CAMPAIGN: 0.15,
  PRICING_CHANGE: 0.20,
};

export function getRunCostEstimate(runType: string): number {
  return COST_ESTIMATES[runType] ?? 0.05;
}
